//
// Created by Angus Goucher on 10/14/2024.
//

#include "H2OString.h"

// This would be generated by some external generator.
#include "BaseReflectedTypes.h"
#include "BaseMacros.h"

H2O::Class* H2O::String::Z_Class = nullptr;
H2O::Class* H2O::String::GetClass() {
    if (Z_Class == nullptr) {
        Z_Class = new H2O::Class("String");
        Z_Class->AddField(new Field(H2O::BaseReflectedTypes::U32_GetClass(), "Size", OFFSET_OF(H2O::String,
            Size)));
    }
    return Z_Class;
}